analysis_options:
  exclude:
    - "**/*.g.dart"

linter:
  rules:
    - camel_case_types
    - camel_case_extensions
    - library_names
    - file_names
    - library_private_types_in_public_api
    - always_declare_return_types
